# Generated by Django 4.1.5 on 2023-01-31 08:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_page_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='Python',
        ),
        migrations.AlterField(
            model_name='page',
            name='example',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
