# Generated by Django 4.1.5 on 2023-01-31 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_language_python_alter_page_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='whichLanguage',
        ),
        migrations.DeleteModel(
            name='Python',
        ),
    ]
